### ISSUE TITLE
First PKI run fails to create ACME certificates

### ISSUE THREAD

**Issue by yuvadm** [debops/ansible-pki#108]
Using this config:
```
pki_acme: True
pki_realms:
  - name: 'test'
    acme: True
    acme_default_subdomains: []
    acme_subject: [ 'cn=test.example.com' ]
    acme_domains: [ 'test.example.com' ]
    domains: [ 'test.example.com' ]
    #acme_ca: 'le-staging'  # uncomment for staging tests
```

After the first debops run, the certificates created are not signed by LE.

Workaround is to manually delete `/etc/pki/realms/test` and then run `debops service/pki` again.
