### ISSUE TITLE
Copy Cert/Key from variable

### ISSUE THREAD

**Issue by MatthewMi11er** [debops/ansible-pki#13]
It would be useful to be able to copy a cert/key from an external CA from a variable instead of having to save it to the `secret` directory first. 

That way I could do something like this:
In vault file:
```yaml
my_crt: |
  -----BEGIN CERTIFICATE-----
  ALKSICERTIFICATESKJOLKJLJ
  ALKSIDKLEVALUEDLKJOLKJLJ
  -----END CERTIFICATE-----
```
In nginx definition:
```yaml
nginx_server_default:
  default: True
  enabled: True
  name: ['my_domain']
  pki_crt: '{{ my_crt }}'
  pki_key: '{{ my_key }}'
```

This doesn't seem possible currently.
