### ISSUE TITLE
certtool failure not reported

### ISSUE THREAD

**Issue by thoemy** [debops/ansible-pki#74]
`pki-realm` may fail to generate a `request.pem` when the `gnutls.conf` file is invalid. In my case it complains about an unknown `uri` option.

```bash
$ certtool --generate-request --template gnutls.conf --load-privkey ../private/key.pem --outfile request.pem.tmp
error parsing command line: gnutls.conf: unknown option 'uri' at position 480 in config file
$ echo $?
11
```
The failure is not visible in the ansible output and one wonders why the realm is not correctly setup.

```yaml
pki_realms:
  - name: 'myrealm'
    authority: 'service'
    internal: True
    subject_alt_names:
      - 'ip:{{ ansible_default_ipv4.address }}'
      - 'uri:https://{{ ansible_domain }}/'
      - 'dns:*.{{ ansible_domain }}'
      - 'dns:{{ ansible_domain }}'
```
Removing the `uri` from the above realm configuration makes things work.

This happened with an older Debian wheezy system.
```bash
$ certtool --version
certtool (GnuTLS) 2.12.20
Packaged by Debian (2.12.20-8+deb7u5)

$ apt-cache policy gnutls-bin 
gnutls-bin:
  Installed: 3.0.22-3+really2.12.20-8+deb7u5
  Candidate: 3.0.22-3+really2.12.20-8+deb7u5
  Version table:
 *** 3.0.22-3+really2.12.20-8+deb7u5 0
        500 http://cdn.debian.net/debian/ wheezy/main amd64 Packages
        500 http://security.debian.org/ wheezy/updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

So the error from the certtool output should probably shown to the user and the task aborted.
